# Merging the INE housing and tourism tables

## 1. Setup

In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## 2. A small helper to read the INE files

The INE exports have a few lines of text on top, several header rows and some notes at the bottom, and those sizes change from file to file. Instead of counting lines by hand, this helper reads the whole file and keeps only the lines that look like data rows (the ones that start with a region code such as `11A: Área Metropolitana do Porto`).

In [2]:
# Reads an INE csv and returns only the data rows, as text columns (X1, X2, ...).
# We convert to numbers later, file by file.
read_ine_rows <- function(path) {
  all_lines <- read_lines(path, locale = locale(encoding = "latin1"))

  # A data row starts with a code like "PT: ", "11A: " or "1D1: ".
  # The population file has a year before the code ("2021;PT: ..."), so we allow that too.
  is_data_row <- str_detect(all_lines, "^(\\d{4})?;?[0-9A-Z]{1,4}: ")

  read_delim(
    I(all_lines[is_data_row]),
    delim = ";",
    col_names = FALSE,
    col_types = cols(.default = col_character()),
    show_col_types = FALSE
  )
}

# Turns text like "1460,8" into the number 1460.8 (the INE uses a decimal comma).
# parse_number leaves floating point noise (9.14 becomes 9.139999999999999), so we round
# to 2 decimals, the most the INE tables use.
to_number <- function(x) round(parse_number(x, locale = locale(decimal_mark = ",")), 2)

## 3. Region lookup

Every file labels regions as `"code: name"`. We read the "new homes" file first just to build one clean list of regions. We keep the **NUTS III** level (3-character codes like `11A` or `1D1`), plus the two island regions, whose code in most files is just `20` and `30`.

In [3]:
homes_raw <- read_ine_rows("data/viviendas_concluidas.csv")

regions <- homes_raw |>
  select(X1) |>
  separate(X1, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  filter(nchar(nuts_code) == 3 | nuts_code %in% c("20", "30"))

regions

   nuts_code region
1  111       Alto Minho
2  112       Cávado
3  119       Ave
4  11A       Área Metropolitana do Porto
5  11B       Alto Tâmega e Barroso
6  11C       Tâmega e Sousa
7  11D       Douro
8  11E       Terras de Trás-os-Montes
9  191       Região de Aveiro
10 192       Região de Coimbra
11 193       Região de Leiria
12 194       Viseu Dão Lafões
13 195       Beira Baixa
14 196       Beiras e Serra da Estrela
15 1D1       Oeste
16 1D2       Médio Tejo
17 1D3       Lezíria do Tejo
18 1A0       Grande Lisboa
19 1B0       Península de Setúbal
20 1C1       Alentejo Litoral
21 1C2       Baixo Alentejo
22 1C3       Alto Alentejo
23 1C4       Alentejo Central
24 150       Algarve
25 20        Região Autónoma dos Açores
26 30        Região Autónoma da Madeira

## 4. Wide tables with one value per year

Four files have the same layout: one row per region and one column per year. For each one we name the year columns, drop the empty trailing column, melt to long format and keep only the regions we care about.

### Monthly wage

In [4]:
wage_raw <- read_ine_rows("data/salario_medio.csv")

wage_years <- 2024:2021   # the years, in the same order as the file columns

wage <- wage_raw |>
  select(1:(length(wage_years) + 1)) |>
  set_names(c("region_raw", wage_years)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "wage_monthly") |>
  mutate(year = as.integer(year), wage_monthly = to_number(wage_monthly)) |>
  select(nuts_code, year, wage_monthly)

wage

    nuts_code year wage_monthly
1   PT        2024 1576.0
2   PT        2023 1460.8
3   PT        2022 1362.4
4   PT        2021 1289.5
5   1         2024 1582.7
6   1         2023 1466.7
7   1         2022 1368.0
8   1         2021 1294.1
9   11        2024 1474.7
10  11        2023 1348.7
11  11        2022 1253.5
12  11        2021 1187.2
13  111       2024 1340.1
14  111       2023 1237.7
15  111       2022 1154.3
16  111       2021 1095.0
17  112       2024 1403.3
18  112       2023 1276.5
19  112       2022 1183.1
20  112       2021 1134.3
21  119       2024 1321.7
22  119       2023 1215.1
23  119       2022 1132.3
24  119       2021 1080.8
25  11A       2024 1620.1
26  11A       2023 1480.1
27  11A       2022 1378.6
28  11A       2021 1301.1
29  11B       2024 1207.1
30  11B       2023 1128.2
⋮   ⋮         ⋮    ⋮
119 1C3       2022 1126.6
120 1C3       2021 1078.9
121 1C4       2024 1372.0
122 1C4       2023 1271.7
123 1C4       2022 1190.6
124 1C4       2021 1127.3
125 15        2024 1320.2
126 15        2023 1238.7
127 15        2022 1150.8
128 15        2021 1106.3
129 150       2024 1320.2
130 150       2023 1238.7
131 150       2022 1150.8
132 150       2021 1106.3
133 2         2024 1431.9
134 2         2023 1315.1
135 2         2022 1191.1
136 2         2021 1126.1
137 20        2024 1431.9
138 20        2023 1315.1
139 20        2022 1191.1
140 20        2021 1126.1
141 3         2024 1406.8
142 3         2023 1324.0
143 3         2022 1244.1
144 3         2021 1212.4
145 30        2024 1406.8
146 30        2023 1324.0
147 30        2022 1244.1
148 30        2021 1212.4

### Median rent per m²

In [5]:
rent_raw <- read_ine_rows("data/renta_mediana_m2.csv")

rent_years <- 2025:2020

rent <- rent_raw |>
  select(1:(length(rent_years) + 1)) |>
  set_names(c("region_raw", rent_years)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "rent_m2") |>
  mutate(year = as.integer(year), rent_m2 = to_number(rent_m2)) |>
  # This file lists the Azores twice (codes 20 and 200). We keep 20, like in the other files.
  filter(nuts_code != "200") |>
  select(nuts_code, year, rent_m2)

rent

    nuts_code year rent_m2
1   PT        2025 9.29
2   PT        2024 8.47
3   PT        2023 7.62
4   PT        2022 6.88
5   PT        2021 6.31
6   PT        2020 5.79
7   1         2025 9.32
8   1         2024 8.50
9   1         2023 7.64
10  1         2022 6.90
11  1         2021 6.34
12  1         2020 5.81
13  11        2025 8.00
14  11        2024 7.22
15  11        2023 6.48
16  11        2022 5.77
17  11        2021 5.29
18  11        2020 4.88
19  111       2025 6.51
20  111       2024 6.00
21  111       2023 5.35
22  111       2022 4.69
23  111       2021 4.29
24  111       2020 4.00
25  112       2025 7.83
26  112       2024 7.38
27  112       2023 6.59
28  112       2022 5.77
29  112       2021 5.14
30  112       2020 4.93
⋮   ⋮         ⋮    ⋮
193 150       2025 10.53
194 150       2024  9.74
195 150       2023  8.61
196 150       2022  7.70
197 150       2021  6.94
198 150       2020  6.73
199 2         2025  5.94
200 2         2024  5.46
201 2         2023  5.15
202 2         2022  4.90
203 2         2021  4.54
204 2         2020  4.47
205 20        2025  5.94
206 20        2024  5.46
207 20        2023  5.15
208 20        2022  4.90
209 20        2021  4.54
210 20        2020  4.47
211 3         2025 11.32
212 3         2024 10.61
213 3         2023  9.16
214 3         2022  7.86
215 3         2021  6.64
216 3         2020  6.32
217 30        2025 11.32
218 30        2024 10.61
219 30        2023  9.16
220 30        2022  7.86
221 30        2021  6.64
222 30        2020  6.32

### New homes completed

In [6]:
homes_years <- 2025:2011

homes <- homes_raw |>
  select(1:(length(homes_years) + 1)) |>
  set_names(c("region_raw", homes_years)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "homes_completed") |>
  mutate(year = as.integer(year), homes_completed = to_number(homes_completed)) |>
  select(nuts_code, year, homes_completed)

homes

    nuts_code year homes_completed
1   PT        2025 27301
2   PT        2024 24666
3   PT        2023 22280
4   PT        2022 21047
5   PT        2021 19926
6   PT        2020 16923
7   PT        2019 12954
8   PT        2018 10751
9   PT        2017  8213
10  PT        2016  7909
11  PT        2015  7148
12  PT        2014  8313
13  PT        2013 12751
14  PT        2012 19684
15  PT        2011 26382
16  1         2025 25984
17  1         2024 23224
18  1         2023 21351
19  1         2022 20062
20  1         2021 19079
21  1         2020 16165
22  1         2019 12312
23  1         2018 10286
24  1         2017  7840
25  1         2016  7544
26  1         2015  6786
27  1         2014  7955
28  1         2013 11902
29  1         2012 18783
30  1         2011 25033
⋮   ⋮         ⋮    ⋮
526 3         2025 871
527 3         2024 927
528 3         2023 439
529 3         2022 588
530 3         2021 379
531 3         2020 414
532 3         2019 295
533 3         2018 180
534 3         2017 163
535 3         2016 144
536 3         2015 126
537 3         2014 173
538 3         2013 362
539 3         2012 363
540 3         2011 649
541 30        2025 871
542 30        2024 927
543 30        2023 439
544 30        2022 588
545 30        2021 379
546 30        2020 414
547 30        2019 295
548 30        2018 180
549 30        2017 163
550 30        2016 144
551 30        2015 126
552 30        2014 173
553 30        2013 362
554 30        2012 363
555 30        2011 649

### Foreign residents

In [7]:
foreign_raw <- read_ine_rows("data/extranjeros_residentes.csv")

foreign_years <- 2023:2021

foreign <- foreign_raw |>
  select(1:(length(foreign_years) + 1)) |>
  set_names(c("region_raw", foreign_years)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "foreign_residents") |>
  mutate(year = as.integer(year), foreign_residents = to_number(foreign_residents)) |>
  select(nuts_code, year, foreign_residents)

foreign

    nuts_code year foreign_residents
1   PT        2023 1044238
2   PT        2022  781247
3   PT        2021  698536
4   1         2023 1023941
5   1         2022  764349
6   1         2021  683669
7   11        2023  174958
8   11        2022  119385
9   11        2021  100084
10  111       2023   13145
11  111       2022    9187
12  111       2021    7505
13  112       2023   28650
14  112       2022   19947
15  112       2021   16781
16  119       2023   13072
17  119       2022    8088
18  119       2021    6803
19  11A       2023  100602
20  11A       2022   69038
21  11A       2021   57970
22  11B       2023    2074
23  11B       2022    1479
24  11B       2021    1398
25  11C       2023    6568
26  11C       2022    4315
27  11C       2021    3528
28  11D       2023    4432
29  11D       2022    2954
30  11D       2021    2559
⋮   ⋮         ⋮    ⋮
82  1C1       2023  19370
83  1C1       2022  16394
84  1C1       2021  14622
85  1C2       2023   7136
86  1C2       2022   5526
87  1C2       2021   5026
88  1C3       2023   3937
89  1C3       2022   3175
90  1C3       2021   2881
91  1C4       2023   7365
92  1C4       2022   5395
93  1C4       2021   4897
94  15        2023 125424
95  15        2022 109636
96  15        2021 105137
97  150       2023 125424
98  150       2022 109636
99  150       2021 105137
100 2         2023   6237
101 2         2022   5105
102 2         2021   4462
103 20        2023   6237
104 20        2022   5105
105 20        2021   4462
106 3         2023  14060
107 3         2022  11793
108 3         2021  10405
109 30        2023  14060
110 30        2022  11793
111 30        2021  10405

## 5. Resident population (yearly estimates, by age)

The INE publishes a yearly estimate of the resident population on 31 December, split into five-year age groups. We use it instead of the Census 2021 count because it gives a population for every year, which is the right denominator for per-capita rates. The two do not match: the yearly estimate is built from administrative records and is higher than the Census in the regions that grew fastest (about 9% more in the Algarve already in 2021). The Census file stays in `data/poblacion_censo2021.csv` but is no longer used.

The year is written only on the first row of each block of regions, so we fill it downwards. We keep the total population and turn the age groups into shares of the population (in %).

In [8]:
population_raw <- read_ine_rows("data/poblacion_anual_edad.csv")

# Columns: X1 year (only on the first row of each block), X2 region, X3 total population
# (both sexes) and X4-X21 the 18 five-year age groups (0-4 ... 85 and over).
# The columns for men and for women that come after are not used.
population_age <- population_raw |>
  mutate(year = as.integer(X1)) |>
  fill(year) |>
  select(year, region_raw = X2, num_range("X", 3:21)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  mutate(across(num_range("X", 3:21), to_number))

population <- population_age |>
  transmute(
    nuts_code, year,
    population   = X3,
    share_0_14   = (X4 + X5 + X6) / X3 * 100,
    share_15_24  = (X7 + X8) / X3 * 100,
    share_25_34  = (X9 + X10) / X3 * 100,
    share_35_44  = (X11 + X12) / X3 * 100,
    share_45_54  = (X13 + X14) / X3 * 100,
    share_55_64  = (X15 + X16) / X3 * 100,
    share_65_79  = (X17 + X18 + X19) / X3 * 100,
    share_80plus = (X20 + X21) / X3 * 100,
    share_20_34  = (X8 + X9 + X10) / X3 * 100   # young adults, the age of most new tenants
  ) |>
  mutate(across(starts_with("share_"), ~ round(.x, 2)))

population

    nuts_code year population share_0_14 share_15_24 share_25_34 share_35_44
1   PT        2025 11424031   12.36      10.30       12.80       13.33
2   1         2025 10912573   12.34      10.27       12.84       13.32
3   11        2025  3790554   11.79      10.16       12.19       12.83
4   111       2025   244343   11.41       9.57       10.90       12.25
5   112       2025   449945   12.81      10.92       12.65       13.64
6   119       2025   441329   12.18      10.06       12.15       13.00
7   11A       2025  1861727   11.79      10.11       12.72       13.19
8   11B       2025    83364    9.71       8.14        8.35       10.11
9   11C       2025   416728   12.11      10.91       12.28       12.62
10  11D       2025   184167   10.31       9.37        9.90       10.76
11  11E       2025   108951    9.63       9.51       10.57       10.19
12  19        2025  1771259   11.69       9.75       11.13       12.23
13  191       2025   400219   12.52      10.10       12.13       13.14
14  192       2025   467375   11.23       9.63       10.95       11.97
15  193       2025   319032   12.45      10.19       11.97       12.84
16  194       2025   267430   11.86       9.83       10.54       12.03
17  195       2025   104118   10.89       9.12       10.04       11.20
18  196       2025   213085   10.17       8.88        9.69       10.94
19  1D        2025   905403   12.59      10.30       11.81       12.71
20  1D1       2025   413287   12.74      10.31       12.31       13.18
21  1D2       2025   227067   12.06      10.00       10.65       11.80
22  1D3       2025   265049   12.80      10.54       12.03       12.74
23  1A        2025  2415261   13.16      10.74       15.31       14.69
24  1A0       2025  2415261   13.16      10.74       15.31       14.69
25  1B        2025   937678   13.64      11.11       13.49       14.06
26  1B0       2025   937678   13.64      11.11       13.49       14.06
27  1C        2025   514386   11.76       9.59       12.15       13.03
28  1C1       2025   118492   10.77       9.15       16.13       16.39
29  1C2       2025   125767   12.27       9.96       12.16       12.70
30  1C3       2025   108485   11.76       9.50        9.81       11.05
⋮   ⋮         ⋮    ⋮          ⋮          ⋮           ⋮           ⋮
156 11B       2021   81869     9.67       8.52        7.90       10.38
157 11C       2021  404148    12.94      12.05       11.63       13.09
158 11D       2021  180409    10.75       9.71        8.87       11.50
159 11E       2021  106574     9.72       9.81        9.06       10.82
160 19        2021 1667125    11.83       9.95        9.91       12.65
161 191       2021  372746    12.93      10.32       10.89       13.53
162 192       2021  442547    11.46       9.76        9.64       12.62
163 193       2021  293854    12.61      10.49       10.62       13.08
164 194       2021  251826    11.92      10.15        9.50       12.60
165 195       2021   98387    10.60       9.00        8.78       11.28
166 196       2021  207765    10.03       9.14        8.72       11.25
167 1D        2021  825229    12.84      10.40        9.91       12.94
168 1D1       2021  372933    13.31      10.55       10.36       13.52
169 1D2       2021  211231    11.72      10.04        9.22       11.84
170 1D3       2021  241065    13.10      10.50        9.84       12.99
171 1A        2021 2184555    14.30      10.67       13.04       14.39
172 1A0       2021 2184555    14.30      10.67       13.04       14.39
173 1B        2021  831113    14.61      10.78       11.16       14.13
174 1B0       2021  831113    14.61      10.78       11.16       14.13
175 1C        2021  485647    12.15       9.67       10.51       12.93
176 1C1       2021  104910    11.41       9.32       13.87       15.10
177 1C2       2021  118514    12.84       9.87       10.35       12.49
178 1C3       2021  106510    11.95       9.56        8.83       11.63
179 1C4       2021  155713    12.26       9.82        9.51       12.70
180 15        2021  507930    13.62       9.77       11.53       14.08
181 150       2021  507930    13.62       9.77       11.53       14.08
182 2         2021  241026    14.77      11.74       12.69       15.33
183 20        2021  241026    14.77      11.74       12.69       15.33
184 3         2021  253129    12.93      11.40       10.47       13.71
185 30        2021  253129    12.93      11.40       10.47       13.71
    share_45_54 share_55_64 share_65_79 share_80plus share_20_34
1   14.75       13.13       16.30        7.04        18.24
2   14.70       13.06       16.34        7.13        18.27
3   14.86       14.16       17.21        6.81        17.56
4   14.35       13.53       18.83        9.16        15.90
5   15.47       13.66       15.18        5.68        18.37
6   15.19       14.64       16.88        5.89        17.46
7   14.98       13.93       16.86        6.41        18.08
8   12.89       14.54       23.87       12.40        12.56
9   15.12       15.20       16.12        5.64        17.99
10  13.77       15.15       20.99        9.76        14.83
11  12.65       13.62       21.85       11.99        16.15
12  14.33       13.65       18.38        8.84        16.28
13  14.80       13.52       16.72        7.07        17.40
14  14.56       13.96       18.68        9.02        16.10
15  14.62       13.29       16.80        7.84        17.33
16  14.22       13.19       18.96        9.36        15.64
17  13.14       13.82       20.34       11.45        14.84
18  13.20       14.29       21.48       11.36        14.47
19  14.64       13.31       16.85        7.79        17.16
20  15.04       13.15       16.33        6.94        17.68
21  13.69       14.04       18.36        9.40        15.79
22  14.83       12.93       16.38        7.73        17.51
23  14.64       11.40       13.66        6.40        21.11
24  14.64       11.40       13.66        6.40        21.11
25  15.22       11.51       14.78        6.19        19.24
26  15.22       11.51       14.78        6.19        19.24
27  14.13       13.23       17.49        8.62        17.27
28  13.98       10.86       15.50        7.21        21.26
29  13.63       13.51       17.61        8.17        17.47
30  14.09       14.37       19.27       10.15        14.71
⋮   ⋮           ⋮           ⋮           ⋮            ⋮
156 12.70       15.73       23.24       11.86        12.19
157 15.82       14.90       14.24        5.33        18.02
158 14.05       15.88       19.81        9.42        13.91
159 12.70       14.59       21.78       11.53        14.75
160 14.38       14.22       18.28        8.78        15.14
161 15.07       13.92       16.44        6.89        16.32
162 14.60       14.43       18.59        8.89        14.81
163 14.73       13.86       16.87        7.74        16.09
164 13.92       13.72       19.08        9.11        14.72
165 13.25       14.61       20.24       12.24        13.62
166 13.24       15.24       21.01       11.37        13.58
167 14.79       13.80       17.32        7.99        15.21
168 15.13       13.43       16.80        6.90        15.70
169 14.12       14.82       18.35        9.90        14.40
170 14.87       13.48       17.23        7.99        15.16
171 14.61       11.81       14.84        6.34        18.64
172 14.61       11.81       14.84        6.34        18.64
173 14.97       12.28       16.08        5.98        16.57
174 14.97       12.28       16.08        5.98        16.57
175 13.91       14.09       17.39        9.35        15.58
176 13.05       13.01       16.24        8.00        19.08
177 13.74       14.26       17.52        8.94        15.48
178 13.98       14.78       18.49       10.79        13.68
179 14.59       14.22       17.33        9.57        14.59
180 14.80       13.39       16.53        6.27        16.49
181 14.80       13.39       16.53        6.27        16.49
182 15.05       13.55       12.67        4.20        18.75
183 15.05       13.55       12.67        4.20        18.75
184 16.09       15.20       14.87        5.33        16.19
185 16.09       15.20       14.87        5.33        16.19

## 5b. More yearly tables: net migration, median income and building permits

Net migration and the median declared income have the same layout as the tables in section 4 (one column per year). The median income comes from tax returns, per taxpayer and per year, and is only used as a check (section 9). Building permits look like the sale prices: 5 columns per year (Total, T0 or T1, T2, T3, T4 or more), and we keep only Total. All three keep every year the file has, so section 7b can use the long permit series.

In [9]:
migration_raw <- read_ine_rows("data/saldo_migratorio.csv")

migration_years <- 2025:2021

net_migration <- migration_raw |>
  select(1:(length(migration_years) + 1)) |>
  set_names(c("region_raw", migration_years)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "net_migration") |>
  mutate(year = as.integer(year), net_migration = to_number(net_migration)) |>
  select(nuts_code, year, net_migration)

income_raw <- read_ine_rows("data/ingreso_mediano.csv")

income_years <- 2024:2018

income <- income_raw |>
  select(1:(length(income_years) + 1)) |>
  set_names(c("region_raw", income_years)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "income_median") |>
  mutate(year = as.integer(year), income_median = to_number(income_median)) |>
  select(nuts_code, year, income_median)

net_migration
income

    nuts_code year net_migration
1   PT        2025  70862
2   PT        2024 216629
3   PT        2023 307288
4   PT        2022 371277
5   PT        2021 250079
6   1         2025  66855
7   1         2024 210034
8   1         2023 300560
9   1         2022 364980
10  1         2021 243986
11  11        2025  24610
12  11        2024  50989
13  11        2023  73117
14  11        2022  86454
15  11        2021  14231
16  111       2025   2144
17  111       2024   4102
18  111       2023   6096
19  111       2022   7788
20  111       2021    124
21  112       2025   2457
22  112       2024   7051
23  112       2023  10181
24  112       2022  13745
25  112       2021   -314
26  119       2025   3503
27  119       2024   5019
28  119       2023   7734
29  119       2022   9063
30  119       2021   -296
⋮   ⋮         ⋮    ⋮
156 15        2025  2233
157 15        2024 14459
158 15        2023 22440
159 15        2022 36662
160 15        2021 39794
161 150       2025  2233
162 150       2024 14459
163 150       2023 22440
164 150       2022 36662
165 150       2021 39794
166 2         2025  1450
167 2         2024  1625
168 2         2023  1657
169 2         2022  1596
170 2         2021  3733
171 20        2025  1450
172 20        2024  1625
173 20        2023  1657
174 20        2022  1596
175 20        2021  3733
176 3         2025  2557
177 3         2024  4970
178 3         2023  5071
179 3         2022  4701
180 3         2021  2360
181 30        2025  2557
182 30        2024  4970
183 30        2023  5071
184 30        2022  4701
185 30        2021  2360

    nuts_code year income_median
1   PT        2024 12666
2   PT        2023 11845
3   PT        2022 11103
4   PT        2021 10540
5   PT        2020 10023
6   PT        2019  9880
7   PT        2018  9431
8   1         2024 12659
9   1         2023 11842
10  1         2022 11108
11  1         2021 10555
12  1         2020 10033
13  1         2019  9893
14  1         2018  9444
15  11        2024 11951
16  11        2023 11085
17  11        2022 10332
18  11        2021  9706
19  11        2020  9191
20  11        2019  9000
21  11        2018  8572
22  111       2024 11646
23  111       2023 10755
24  111       2022  9993
25  111       2021  9427
26  111       2020  8951
27  111       2019  8728
28  111       2018  8317
29  112       2024 12116
30  112       2023 11240
⋮   ⋮         ⋮    ⋮
230 150       2019  9503
231 150       2018  9143
232 2         2024 12766
233 2         2023 11893
234 2         2022 11013
235 2         2021 10279
236 2         2020  9858
237 2         2019  9529
238 2         2018  9064
239 20        2024 12766
240 20        2023 11893
241 20        2022 11013
242 20        2021 10279
243 20        2020  9858
244 20        2019  9529
245 20        2018  9064
246 3         2024 12840
247 3         2023 11922
248 3         2022 10973
249 3         2021 10270
250 3         2020  9838
251 3         2019  9762
252 3         2018  9329
253 30        2024 12840
254 30        2023 11922
255 30        2022 10973
256 30        2021 10270
257 30        2020  9838
258 30        2019  9762
259 30        2018  9329

In [10]:
permits_raw <- read_ine_rows("data/viviendas_licenciadas.csv")

permits_years <- 2025:2002
permits_sizes <- c("total", "t0t1", "t2", "t3", "t4plus")

permits_col_names <- paste0(rep(permits_years, each = length(permits_sizes)), "_", permits_sizes)

permits <- permits_raw |>
  select(1:(length(permits_col_names) + 1)) |>
  set_names(c("region_raw", permits_col_names)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year_size", values_to = "homes_licensed") |>
  separate(year_size, into = c("year", "size"), sep = "_") |>
  filter(size == "total") |>
  mutate(year = as.integer(year), homes_licensed = to_number(homes_licensed)) |>
  select(nuts_code, year, homes_licensed)
permits

    nuts_code year homes_licensed
1   PT        2025 42066
2   PT        2024 35371
3   PT        2023 33560
4   PT        2022 32232
5   PT        2021 30094
6   PT        2020 26168
7   PT        2019 25824
8   PT        2018 21896
9   PT        2017 14967
10  PT        2016 11817
11  PT        2015  8686
12  PT        2014  6996
13  PT        2013  7494
14  PT        2012 11512
15  PT        2011 17615
16  PT        2010 25002
17  PT        2009 27298
18  PT        2008 45981
19  PT        2007 65828
20  PT        2006 71921
21  PT        2005 73922
22  PT        2004 77115
23  PT        2003 81546
24  PT        2002 95673
25  1         2025 40335
26  1         2024 33588
27  1         2023 31926
28  1         2022 30917
29  1         2021 28631
30  1         2020 25123
⋮   ⋮         ⋮    ⋮
859 3         2007 1811
860 3         2006 2054
861 3         2005 3187
862 3         2004 4126
863 3         2003 2844
864 3         2002 3127
865 30        2025  980
866 30        2024 1121
867 30        2023 1118
868 30        2022  680
869 30        2021  839
870 30        2020  502
871 30        2019  374
872 30        2018  328
873 30        2017  353
874 30        2016  190
875 30        2015  113
876 30        2014  139
877 30        2013  131
878 30        2012  249
879 30        2011  485
880 30        2010  509
881 30        2009  608
882 30        2008 1655
883 30        2007 1811
884 30        2006 2054
885 30        2005 3187
886 30        2004 4126
887 30        2003 2844
888 30        2002 3127

## 5c. Census 2021 tenure and the 2022 housing stock

These two tables have a single year, so they become fixed columns repeated on every row of the region:

- `households_2021` and `rented_households_2021`: households living in their usual home, in total and those who rent (Census 2021).
- `dwellings_2022`: all classic family dwellings in 2022 (the INE estimate of the housing stock).

In [11]:
tenure_raw <- read_ine_rows("data/hogares_regimen_2021.csv")

# Columns after the region: total, owned, rented, other arrangement.
tenure <- tenure_raw |>
  select(region_raw = X1, households_2021 = X2, rented_households_2021 = X4) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  mutate(across(c(households_2021, rented_households_2021), to_number)) |>
  select(nuts_code, households_2021, rented_households_2021)

stock_raw <- read_ine_rows("data/parque_viviendas_2022.csv")

stock <- stock_raw |>
  select(region_raw = X1, dwellings_2022 = X2) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  mutate(dwellings_2022 = to_number(dwellings_2022)) |>
  select(nuts_code, dwellings_2022)

tenure
stock

   nuts_code households_2021 rented_households_2021
1  PT        4142581         922810
2  1         3962715         891434
3  11        1379430         306252
4  111         90671          13534
5  112        149713          27256
6  119        153389          34832
7  11A        681349         186037
8  11B         35735           3427
9  11C        148102          25918
10 11D         75043           9621
11 11E         45428           5627
12 19         674187         104470
13 191        143268          25323
14 192        180264          29221
15 193        116340          17275
16 194        100823          13376
17 195         43234           5539
18 196         90258          13736
19 1D         329685          54607
20 1D1        146273          25961
21 1D2         87423          12803
22 1D3         95989          15843
23 1A         858646         269489
24 1A0        858646         269489
25 1B         332717          78505
26 1B0        332717          78505
27 1C         194655          33566
28 1C1         39618           6304
29 1C2         47386           5464
30 1C3         43925           8448
31 1C4         63726          13350
32 15         193395          44545
33 150        193395          44545
34 2           85074          14653
35 20          85074          14653
36 3           94792          16723
37 30          94792          16723

   nuts_code dwellings_2022
1  PT        6003809
2  1         5757767
3  11        1908900
4  111        156185
5  112        202322
6  119        200498
7  11A        842440
8  11B         73457
9  11C        205637
10 11D        140855
11 11E         87506
12 19        1102912
13 191        197876
14 192        285411
15 193        174368
16 194        172651
17 195         89254
18 196        183352
19 1D         511691
20 1D1        229656
21 1D2        144739
22 1D3        137296
23 1A        1072111
24 1A0       1072111
25 1B         431921
26 1B0        431921
27 1C         336845
28 1C1         70939
29 1C2         85508
30 1C3         81295
31 1C4         99103
32 15         393387
33 150        393387
34 2          113945
35 20         113945
36 3          132097
37 30         132097

## 6. Median sale price per m²

This one has 5 columns for every year: Total, T0 or T1, T2, T3 and T4 or more. We build the column names by hand (year + size) so we can find each column, and then keep only **Total**.

Total is the INE's median sale price per m² over *all* the dwellings sold in the region. It is not the average of the four sizes (a median of all sales cannot be rebuilt from the medians of the groups), so it is the right single indicator and we drop the four size columns.

In [12]:
sales_raw <- read_ine_rows("data/precio_venta_m2.csv")

sales_years <- 2025:2019
sales_sizes <- c("total", "t0t1", "t2", "t3", "t4plus")

sales_col_names <- paste0(rep(sales_years, each = length(sales_sizes)), "_", sales_sizes)

sales <- sales_raw |>
  select(1:(length(sales_col_names) + 1)) |>
  set_names(c("region_raw", sales_col_names)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "year_size", values_to = "price") |>
  separate(year_size, into = c("year", "size"), sep = "_") |>
  filter(size == "total") |>
  mutate(year = as.integer(year), sale_price_m2 = to_number(price)) |>
  select(nuts_code, year, sale_price_m2)
sales

    nuts_code year sale_price_m2
1   PT        2025 2076
2   PT        2024 1777
3   PT        2023 1611
4   PT        2022 1484
5   PT        2021 1297
6   PT        2020 1190
7   PT        2019 1094
8   1         2025 2083
9   1         2024 1778
10  1         2023 1618
11  1         2022 1492
12  1         2021 1301
13  1         2020 1195
14  1         2019 1096
15  11        2025 1825
16  11        2024 1558
17  11        2023 1394
18  11        2022 1282
19  11        2021 1133
20  11        2020 1047
21  11        2019  948
22  111       2025 1401
23  111       2024 1248
24  111       2023 1108
25  111       2022 1064
26  111       2021  945
27  111       2020  891
28  111       2019  846
29  112       2025 1805
30  112       2024 1527
⋮   ⋮         ⋮    ⋮
230 150       2020 1816
231 150       2019 1696
232 2         2025 1426
233 2         2024 1179
234 2         2023 1105
235 2         2022 1034
236 2         2021  903
237 2         2020  874
238 2         2019  779
239 20        2025 1426
240 20        2024 1179
241 20        2023 1105
242 20        2022 1034
243 20        2021  903
244 20        2020  874
245 20        2019  779
246 3         2025 2500
247 3         2024 2395
248 3         2023 1889
249 3         2022 1571
250 3         2021 1436
251 3         2020 1303
252 3         2019 1214
253 30        2025 2500
254 30        2024 2395
255 30        2023 1889
256 30        2022 1571
257 30        2021 1436
258 30        2020 1303
259 30        2019 1214

## 7. Overnight stays (monthly -\> yearly)

The tourism file uses the same **NUTS 2024** map as the other files and has one column per month ("Agosto de 2026", "Julho de 2026", ...). Two things to do here:

1.  Keep only the regions in our list (this drops the country, NUTS I / NUTS II rows and the duplicated Azores row `200`).
2.  Add up the 12 months of each year. We only keep 2022-2025: the file starts in January 2022 and 2026 is incomplete.

In [13]:
stays_lines <- read_lines(
  "data/turismo_noches.csv",
  locale = locale(encoding = "latin1")
)

# The header line with the months is the one that starts with ";Agosto de 2026;Julho de 2026..."
month_header <- stays_lines[str_detect(stays_lines, "^;[A-Za-zç]+ de \\d{4};")]
month_names  <- str_split(month_header, ";")[[1]]
month_names  <- month_names[month_names != ""]   # drop the empty bits

stays_raw <- read_ine_rows("data/turismo_noches.csv")

stays_monthly <- stays_raw |>
  select(1:(length(month_names) + 1)) |>
  set_names(c("region_raw", month_names)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "month", values_to = "tourist_nights") |>
  mutate(
    year = as.integer(str_extract(month, "\\d{4}")),
    tourist_nights = to_number(tourist_nights)
  )
stays_monthly

     nuts_code region                     month             tourist_nights year
1    PT        Portugal                   Agosto de 2026    10886445       2026
2    PT        Portugal                   Julho de 2026      9583880       2026
3    PT        Portugal                   Junho de 2026      8131586       2026
4    PT        Portugal                   Maio de 2026       7996616       2026
5    PT        Portugal                   Abril de 2026      7150714       2026
6    PT        Portugal                   Março de 2026      5625115       2026
7    PT        Portugal                   Fevereiro de 2026  4203862       2026
8    PT        Portugal                   Janeiro de 2026    3741952       2026
9    PT        Portugal                   Dezembro de 2025   4260786       2025
10   PT        Portugal                   Novembro de 2025   5036891       2025
11   PT        Portugal                   Outubro de 2025    7712397       2025
12   PT        Portugal                   Setembro de 2025   8509433       2025
13   PT        Portugal                   Agosto de 2025    10700547       2025
14   PT        Portugal                   Julho de 2025      9412435       2025
15   PT        Portugal                   Junho de 2025      8074409       2025
16   PT        Portugal                   Maio de 2025       7801025       2025
17   PT        Portugal                   Abril de 2025      7123799       2025
18   PT        Portugal                   Março de 2025      5556754       2025
19   PT        Portugal                   Fevereiro de 2025  4163822       2025
20   PT        Portugal                   Janeiro de 2025    3659360       2025
21   PT        Portugal                   Dezembro de 2024   4153763       2024
22   PT        Portugal                   Novembro de 2024   5009564       2024
23   PT        Portugal                   Outubro de 2024    7565935       2024
24   PT        Portugal                   Setembro de 2024   8453759       2024
25   PT        Portugal                   Agosto de 2024    10553909       2024
26   PT        Portugal                   Julho de 2024      9061766       2024
27   PT        Portugal                   Junho de 2024      7841978       2024
28   PT        Portugal                   Maio de 2024       7701923       2024
29   PT        Portugal                   Abril de 2024      6548855       2024
30   PT        Portugal                   Março de 2024      5725068       2024
⋮    ⋮         ⋮                          ⋮                 ⋮              ⋮
2099 30        Região Autónoma da Madeira Junho de 2024     862161         2024
2100 30        Região Autónoma da Madeira Maio de 2024      868449         2024
2101 30        Região Autónoma da Madeira Abril de 2024     788530         2024
2102 30        Região Autónoma da Madeira Março de 2024     764598         2024
2103 30        Região Autónoma da Madeira Fevereiro de 2024 651234         2024
2104 30        Região Autónoma da Madeira Janeiro de 2024   582505         2024
2105 30        Região Autónoma da Madeira Dezembro de 2023  583635         2023
2106 30        Região Autónoma da Madeira Novembro de 2023  677429         2023
2107 30        Região Autónoma da Madeira Outubro de 2023   829136         2023
2108 30        Região Autónoma da Madeira Setembro de 2023  876902         2023
2109 30        Região Autónoma da Madeira Agosto de 2023    982207         2023
2110 30        Região Autónoma da Madeira Julho de 2023     926285         2023
2111 30        Região Autónoma da Madeira Junho de 2023     827025         2023
2112 30        Região Autónoma da Madeira Maio de 2023      814937         2023
2113 30        Região Autónoma da Madeira Abril de 2023     787942         2023
2114 30        Região Autónoma da Madeira Março de 2023     731700         2023
2115 30        Região Autónoma da Madeira Fevereiro de 2023 615367         2023
2116 30        Região Autónoma da Madeira Janeiro de 2023   591405         2023
2117 30        Região Autónoma da Madeira Dezembro de 2022  573340         2022
2118 30        Região Autónoma da Madeira Novembro de 2022  635918         2022
2119 30        Região Autónoma da Madeira Outubro de 2022   782971         2022
2120 30        Região Autónoma da Madeira Setembro de 2022  833578         2022
2121 30        Região Autónoma da Madeira Agosto de 2022    977217         2022
2122 30        Região Autónoma da Madeira Julho de 2022     916058         2022
2123 30        Região Autónoma da Madeira Junho de 2022     822591         2022
2124 30        Região Autónoma da Madeira Maio de 2022      779420         2022
2125 30        Região Autónoma da Madeira Abril de 2022     735252         2022
2126 30        Região Autónoma da Madeira Março de 2022     579890         2022
2127 30        Região Autónoma da Madeira Fevereiro de 2022 396171         2022
2128 30        Região Autónoma da Madeira Janeiro de 2022   348127         2022

The codes in the tourism file already match the other files (including Lisbon, which is split into `1A0` and `1B0`), so no translation table is needed. We just join with the region list.

In [14]:
stays <- stays_monthly |>
  inner_join(regions |> select(nuts_code), by = "nuts_code") |>   # also drops country / NUTS I / NUTS II rows
  filter(year >= 2022, year <= 2025) |>                          # full years only
  group_by(nuts_code, year) |>
  summarise(tourist_nights = sum(tourist_nights), .groups = "drop")

stays

    nuts_code year tourist_nights
1   111       2022  860775
2   111       2023  928528
3   111       2024  985240
4   111       2025 1031079
5   112       2022 1058649
6   112       2023 1119300
7   112       2024 1167899
8   112       2025 1183221
9   119       2022  584132
10  119       2023  651823
11  119       2024  674977
12  119       2025  698406
13  11A       2022 7470106
14  11A       2023 8898492
15  11A       2024 9514850
16  11A       2025 9973516
17  11B       2022  293084
18  11B       2023  318180
19  11B       2024  338972
20  11B       2025  363638
21  11C       2022  443278
22  11C       2023  446775
23  11C       2024  487280
24  11C       2025  517475
25  11D       2022  589456
26  11D       2023  620384
27  11D       2024  649721
28  11D       2025  668247
29  11E       2022  257165
30  11E       2023  279134
⋮   ⋮         ⋮    ⋮
75  1C2       2024  472961
76  1C2       2025  510875
77  1C3       2022  450121
78  1C3       2023  457538
79  1C3       2024  478683
80  1C3       2025  480475
81  1C4       2022  918909
82  1C4       2023 1016851
83  1C4       2024 1064856
84  1C4       2025 1114694
85  1D1       2022 1414061
86  1D1       2023 1606783
87  1D1       2024 1593554
88  1D1       2025 1596723
89  1D2       2022 1127158
90  1D2       2023 1448542
91  1D2       2024 1606495
92  1D2       2025 1631345
93  1D3       2022  229741
94  1D3       2023  264230
95  1D3       2024  282129
96  1D3       2025  277164
97  20        2022 2458031
98  20        2023 2742352
99  20        2024 3027576
100 20        2025 3109259
101 30        2022 8380533
102 30        2023 9243970
103 30        2024 9552517
104 30        2025 9926753

## 7b. Historical series for the trend charts

The figure has two time-series charts that need more years than the main table: sale prices since 2019 and construction since 2002. We save them as two small, separate CSV files, with Portugal (`PT`) as a reference line:

- `data/precios_historicos.csv`: median sale price per m² (2019-2025) and median rent per m² (2020-2025, empty in 2019).
- `data/construccion_historica.csv`: homes licensed (2002-2025) and homes completed (2011-2025, empty before).

In [15]:
history_regions <- bind_rows(tibble(nuts_code = "PT", region = "Portugal"), regions)

price_history <- expand_grid(history_regions, year = 2019:2025) |>
  left_join(sales, by = c("nuts_code", "year")) |>
  left_join(rent,  by = c("nuts_code", "year")) |>
  arrange(nuts_code, year)

construction_history <- expand_grid(history_regions, year = 2002:2025) |>
  left_join(permits, by = c("nuts_code", "year")) |>
  left_join(homes,   by = c("nuts_code", "year")) |>
  arrange(nuts_code, year)

write_csv(price_history, "data/precios_historicos.csv")
write_csv(construction_history, "data/construccion_historica.csv")

# 27 codes (Portugal + 26 regions): 27 x 7 = 189 and 27 x 24 = 648 rows.
nrow(price_history)
nrow(construction_history)

[1] 189

[1] 648

## 8. Join everything

We start from a "skeleton" with every region for every year from 2021 to 2024, and then attach each table to it. Where a table has no data for a given region and year, the value stays `NA` (the equivalent of `NaN` in pandas).

Why 2021-2024? Each source covers different years: wage 2021-2024, median income 2018-2024, rent 2020-2025, sale price 2019-2025, new homes 2011-2025, building permits 2002-2025, foreign residents 2021-2023, tourism 2022-2025, population and net migration 2021-2025. No year has everything, but 2021-2024 has almost all of them in the four years. It also keeps 2021 as the starting point to see how rent affordability changed. The only gaps are tourism in 2021 and foreign residents in 2024.

The Census 2021 tenure and the 2022 housing stock have a single value per region, so they are joined by region only and repeated on every year.

In [16]:
wage

    nuts_code year wage_monthly
1   PT        2024 1576.0
2   PT        2023 1460.8
3   PT        2022 1362.4
4   PT        2021 1289.5
5   1         2024 1582.7
6   1         2023 1466.7
7   1         2022 1368.0
8   1         2021 1294.1
9   11        2024 1474.7
10  11        2023 1348.7
11  11        2022 1253.5
12  11        2021 1187.2
13  111       2024 1340.1
14  111       2023 1237.7
15  111       2022 1154.3
16  111       2021 1095.0
17  112       2024 1403.3
18  112       2023 1276.5
19  112       2022 1183.1
20  112       2021 1134.3
21  119       2024 1321.7
22  119       2023 1215.1
23  119       2022 1132.3
24  119       2021 1080.8
25  11A       2024 1620.1
26  11A       2023 1480.1
27  11A       2022 1378.6
28  11A       2021 1301.1
29  11B       2024 1207.1
30  11B       2023 1128.2
⋮   ⋮         ⋮    ⋮
119 1C3       2022 1126.6
120 1C3       2021 1078.9
121 1C4       2024 1372.0
122 1C4       2023 1271.7
123 1C4       2022 1190.6
124 1C4       2021 1127.3
125 15        2024 1320.2
126 15        2023 1238.7
127 15        2022 1150.8
128 15        2021 1106.3
129 150       2024 1320.2
130 150       2023 1238.7
131 150       2022 1150.8
132 150       2021 1106.3
133 2         2024 1431.9
134 2         2023 1315.1
135 2         2022 1191.1
136 2         2021 1126.1
137 20        2024 1431.9
138 20        2023 1315.1
139 20        2022 1191.1
140 20        2021 1126.1
141 3         2024 1406.8
142 3         2023 1324.0
143 3         2022 1244.1
144 3         2021 1212.4
145 30        2024 1406.8
146 30        2023 1324.0
147 30        2022 1244.1
148 30        2021 1212.4

In [17]:
skeleton <- expand_grid(regions, year = 2021:2024)

merged <- skeleton |>
  left_join(wage,          by = c("nuts_code", "year")) |>
  left_join(income,        by = c("nuts_code", "year")) |>
  left_join(rent,          by = c("nuts_code", "year")) |>
  left_join(sales,         by = c("nuts_code", "year")) |>
  left_join(homes,         by = c("nuts_code", "year")) |>
  left_join(permits,       by = c("nuts_code", "year")) |>
  left_join(foreign,       by = c("nuts_code", "year")) |>
  left_join(population,    by = c("nuts_code", "year")) |>
  left_join(net_migration, by = c("nuts_code", "year")) |>
  left_join(stays,         by = c("nuts_code", "year")) |>
  left_join(tenure,        by = "nuts_code") |>   # Census 2021, repeated on every year
  left_join(stock,         by = "nuts_code") |>   # 2022, repeated on every year
  arrange(nuts_code, year)

glimpse(merged)

Rows: 104
Columns: 25
$ nuts_code              <chr> "111", "111", "111", "111", "112", "112", "112"…
$ region                 <chr> "Alto Minho", "Alto Minho", "Alto Minho", "Alto…
$ year                   <int> 2021, 2022, 2023, 2024, 2021, 2022, 2023, 2024,…
$ wage_monthly           <dbl> 1095.0, 1154.3, 1237.7, 1340.1, 1134.3, 1183.1,…
$ income_median          <dbl> 9427, 9993, 10755, 11646, 9897, 10474, 11240, 1…
$ rent_m2                <dbl> 4.29, 4.69, 5.35, 6.00, 5.14, 5.77, 6.59, 7.38,…
$ sale_price_m2          <dbl> 945, 1064, 1108, 1248, 1091, 1230, 1385, 1527, …
$ homes_completed        <dbl> 588, 596, 581, 656, 1362, 1706, 1465, 1471, 121…
$ homes_licensed         <dbl> 745, 888, 1108, 941, 1754, 2008, 2066, 2146, 17…
$ foreign_residents      <dbl> 7505, 9187, 13145, NA, 16781, 19947, 28650, NA,…
$ population             <dbl> 230770, 236830, 241424, 243852, 417412, 430802,…
$ share_0_14             <dbl> 11.57, 11.65, 11.58, 11.52, 13.54, 13.54, 13.29…
$ share_15_24            <dbl> 9.77, 9.91, 9.87, 9.77, 11.45, 11.42, 11.36, 11…
$ share_25_34            <dbl> 9.96, 10.41, 10.77, 10.85, 11.82, 12.20, 12.48,…
$ share_35_44            <dbl> 12.59, 12.54, 12.46, 12.35, 14.22, 14.04, 13.88…
$ share_45_54            <dbl> 14.34, 14.28, 14.28, 14.29, 15.62, 15.55, 15.54…
$ share_55_64            <dbl> 14.05, 13.80, 13.61, 13.55, 13.66, 13.50, 13.45…
$ share_65_79            <dbl> 18.75, 18.63, 18.65, 18.73, 14.31, 14.43, 14.62…
$ share_80plus           <dbl> 8.96, 8.78, 8.78, 8.93, 5.38, 5.32, 5.38, 5.48,…
$ share_20_34            <dbl> 15.03, 15.60, 16.00, 16.00, 17.78, 18.22, 18.49…
$ net_migration          <dbl> 124, 7788, 6096, 4102, -314, 13745, 10181, 7051…
$ tourist_nights         <dbl> NA, 860775, 928528, 985240, NA, 1058649, 111930…
$ households_2021        <dbl> 90671, 90671, 90671, 90671, 149713, 149713, 149…
$ rented_households_2021 <dbl> 13534, 13534, 13534, 13534, 27256, 27256, 27256…
$ dwellings_2022         <dbl> 156185, 156185, 156185, 156185, 202322, 202322,…

In [18]:
merged

    nuts_code region                      year wage_monthly income_median
1   111       Alto Minho                  2021 1095.0        9427
2   111       Alto Minho                  2022 1154.3        9993
3   111       Alto Minho                  2023 1237.7       10755
4   111       Alto Minho                  2024 1340.1       11646
5   112       Cávado                      2021 1134.3        9897
6   112       Cávado                      2022 1183.1       10474
7   112       Cávado                      2023 1276.5       11240
8   112       Cávado                      2024 1403.3       12116
9   119       Ave                         2021 1080.8        9506
10  119       Ave                         2022 1132.3       10108
11  119       Ave                         2023 1215.1       10819
12  119       Ave                         2024 1321.7       11677
13  11A       Área Metropolitana do Porto 2021 1301.1       10443
14  11A       Área Metropolitana do Porto 2022 1378.6       11037
15  11A       Área Metropolitana do Porto 2023 1480.1       11841
16  11A       Área Metropolitana do Porto 2024 1620.1       12694
17  11B       Alto Tâmega e Barroso       2021  995.1        8350
18  11B       Alto Tâmega e Barroso       2022 1043.4        8997
19  11B       Alto Tâmega e Barroso       2023 1128.2        9637
20  11B       Alto Tâmega e Barroso       2024 1207.1       10523
21  11C       Tâmega e Sousa              2021  980.7        8657
22  11C       Tâmega e Sousa              2022 1026.1        9302
23  11C       Tâmega e Sousa              2023 1107.2        9938
24  11C       Tâmega e Sousa              2024 1210.7       10728
25  11D       Douro                       2021 1031.5        9073
26  11D       Douro                       2022 1089.1        9694
27  11D       Douro                       2023 1168.8       10342
28  11D       Douro                       2024 1268.7       11258
29  11E       Terras de Trás-os-Montes    2021 1021.9        9310
30  11E       Terras de Trás-os-Montes    2022 1066.7        9888
⋮   ⋮         ⋮                           ⋮    ⋮            ⋮
75  1C2       Baixo Alentejo              2023 1401.3       11462
76  1C2       Baixo Alentejo              2024 1469.2       12281
77  1C3       Alto Alentejo               2021 1078.9        9977
78  1C3       Alto Alentejo               2022 1126.6       10567
79  1C3       Alto Alentejo               2023 1197.9       11357
80  1C3       Alto Alentejo               2024 1295.4       12211
81  1C4       Alentejo Central            2021 1127.3       10662
82  1C4       Alentejo Central            2022 1190.6       11250
83  1C4       Alentejo Central            2023 1271.7       12017
84  1C4       Alentejo Central            2024 1372.0       12859
85  1D1       Oeste                       2021 1106.8       10188
86  1D1       Oeste                       2022 1152.4       10766
87  1D1       Oeste                       2023 1237.7       11480
88  1D1       Oeste                       2024 1324.4       12322
89  1D2       Médio Tejo                  2021 1126.7       10306
90  1D2       Médio Tejo                  2022 1175.7       10863
91  1D2       Médio Tejo                  2023 1259.3       11608
92  1D2       Médio Tejo                  2024 1367.1       12462
93  1D3       Lezíria do Tejo             2021 1120.1       10402
94  1D3       Lezíria do Tejo             2022 1178.1       10926
95  1D3       Lezíria do Tejo             2023 1260.7       11601
96  1D3       Lezíria do Tejo             2024 1363.6       12510
97  20        Região Autónoma dos Açores  2021 1126.1       10279
98  20        Região Autónoma dos Açores  2022 1191.1       11013
99  20        Região Autónoma dos Açores  2023 1315.1       11893
100 20        Região Autónoma dos Açores  2024 1431.9       12766
101 30        Região Autónoma da Madeira  2021 1212.4       10270
102 30        Região Autónoma da Madeira  2022 1244.1       10973
103 30        Região Autónoma da Madeira  2023 1324.0       11922
104 30        Região Autónoma da Madeira  2024 1406.8       12840
    rent_m2 sale_price_m2 homes_completed homes_licensed foreign_residents ⋯
1   4.29     945           588             745             7505            ⋯
2   4.69    1064           596             888             9187            ⋯
3   5.35    1108           581            1108            13145            ⋯
4   6.00    1248           656             941               NA            ⋯
5   5.14    1091          1362            1754            16781            ⋯
6   5.77    1230          1706            2008            19947            ⋯
7   6.59    1385          1465            2066            28650            ⋯
8   7.38    1527          1471            2146               NA            ⋯
9   3.76     976          1216            1799             6803            ⋯
10  4.14    1050          1225            1816             8088            ⋯
11  4.69    1150          1237            1956            13072            ⋯
12  5.26    1256          1010            1653               NA            ⋯
13  6.57    1370          4023            6665            57970            ⋯
14  7.29    1607          3743            7474            69038            ⋯
15  8.21    1800          5027            8494           100602            ⋯
16  9.14    1986          5804            8915               NA            ⋯
17  3.50     641           142             210             1398            ⋯
18  3.75     738           172             279             1479            ⋯
19  4.00     735           168             168             2074            ⋯
20  4.17     817           165             216               NA            ⋯
21  3.03     780           893            1247             3528            ⋯
22  3.26     859           851            1197             4315            ⋯
23  3.68     913           999            1232             6568            ⋯
24  4.05     983           949            1462               NA            ⋯
25  3.50     636           271             369             2559            ⋯
26  3.68     653           278             364             2954            ⋯
27  4.00     654           256             439             4432            ⋯
28  4.35     622           249             338               NA            ⋯
29  2.90     635           220             444             3540            ⋯
30  3.01     705           309             296             4377            ⋯
⋮   ⋮       ⋮             ⋮               ⋮              ⋮                 ⋱
75   4.71    629           117             129            7136             ⋯
76   5.29    688           110             123              NA             ⋯
77   3.01    473            97             132            2881             ⋯
78   3.40    500           121              79            3175             ⋯
79   3.60    520            83              98            3937             ⋯
80   4.13    590            87             174              NA             ⋯
81   4.14    784           180             205            4897             ⋯
82   4.45    917           147             297            5395             ⋯
83   4.97    961           179             166            7365             ⋯
84   5.37   1002           182             201              NA             ⋯
85   4.85   1138           867            1277           23487             ⋯
86   5.41   1297           880            1597           26835             ⋯
87   6.25   1469          1153            1446           36103             ⋯
88   7.06   1613          1281            1726              NA             ⋯
89   3.77    655           192             434            7310             ⋯
90   4.24    740           311             337            8419             ⋯
91   4.94    833           223             315           12055             ⋯
92   5.56    937           292             475              NA             ⋯
93   4.24    822           253             390           12276             ⋯
94   4.63    935           318             450           13867             ⋯
95   5.26   1061           375             493           18493             ⋯
96   6.03   1218           412             449              NA             ⋯
97   4.54    903           468             624            4462             ⋯
98   4.90   1034           397             635            5105             ⋯
99   5.15   1105           490             516            6237             ⋯
100  5.46   1179           515             662              NA             ⋯
101  6.64   1436           379             839           10405             ⋯
102  7.86   1571           588             680           11793             ⋯
103  9.16   1889           439            1118           14060             ⋯
104 10.61   2395           927            1121              NA             ⋯
    share_45_54 share_55_64 share_65_79 share_80plus share_20_34 net_migration
1   14.34       14.05       18.75        8.96        15.03         124
2   14.28       13.80       18.63        8.78        15.60        7788
3   14.28       13.61       18.65        8.78        16.00        6096
4   14.29       13.55       18.73        8.93        16.00        4102
5   15.62       13.66       14.31        5.38        17.78        -314
6   15.55       13.50       14.43        5.32        18.22       13745
7   15.54       13.45       14.62        5.38        18.49       10181
8   15.48       13.53       14.90        5.48        18.46        7051
9   15.67       14.67       15.60        5.49        17.31        -296
10  15.53       14.61       15.86        5.47        17.59        9063
11  15.39       14.58       16.22        5.53        17.69        7734
12  15.24       14.62       16.62        5.66        17.57        5019
13  15.33       14.31       16.34        5.90        16.86       24390
14  15.19       14.13       16.41        5.89        17.48       43994
15  15.08       13.99       16.50        6.02        17.95       37359
16  15.02       13.92       16.69        6.15        18.11       25522
17  12.70       15.73       23.24       11.86        12.19       -1776
18  12.62       15.44       23.39       11.84        12.48        1519
19  12.56       15.15       23.61       11.97        12.65        1500
20  12.70       14.87       23.80       12.19        12.54        1357
21  15.82       14.90       14.24        5.33        18.02       -5258
22  15.66       15.02       14.69        5.29        18.12        5142
23  15.45       15.11       15.16        5.35        18.18        4981
24  15.26       15.17       15.70        5.49        18.06        3485
25  14.05       15.88       19.81        9.42        13.91       -2661
26  13.97       15.66       20.04        9.36        14.26        2810
27  13.80       15.50       20.18        9.51        14.66        3256
28  13.76       15.28       20.56        9.61        14.81        2702
29  12.70       14.59       21.78       11.53        14.75          22
30  12.55       14.30       21.66       11.43        15.56        2393
⋮   ⋮           ⋮           ⋮           ⋮            ⋮           ⋮
75  13.58       13.62       17.33        8.23        17.37        4414
76  13.51       13.54       17.27        8.17        17.61        2314
77  13.98       14.78       18.49       10.79        13.68        2214
78  14.13       14.76       18.58       10.48        13.99        1926
79  14.11       14.57       18.73       10.29        14.33        2210
80  14.02       14.44       18.97       10.19        14.60        1561
81  14.59       14.22       17.33        9.57        14.59        3707
82  14.69       14.15       17.30        9.23        15.18        3786
83  14.58       14.06       17.24        9.11        15.76        3703
84  14.59       13.97       17.38        8.99        15.93        2225
85  15.13       13.43       16.80        6.90        15.70        9401
86  15.09       13.27       16.55        6.72        16.53       16935
87  14.97       13.15       16.34        6.73        17.30       14198
88  14.99       13.06       16.29        6.80        17.63       10118
89  14.12       14.82       18.35        9.90        14.40        1527
90  14.01       14.58       18.26        9.67        14.86        6897
91  13.86       14.41       18.14        9.54        15.34        6578
92  13.71       14.21       18.21        9.43        15.62        5625
93  14.87       13.48       17.23        7.99        15.16        5624
94  14.92       13.23       16.86        7.77        16.05        9649
95  14.79       12.97       16.54        7.70        16.98        9593
96  14.76       12.88       16.38        7.66        17.49        6786
97  15.05       13.55       12.67        4.20        18.75        3733
98  15.34       13.72       13.10        4.13        18.61        1596
99  15.48       13.83       13.55        4.20        18.38        1657
100 15.63       13.89       13.96        4.32        18.27        1625
101 16.09       15.20       14.87        5.33        16.19        2360
102 16.03       15.37       15.19        5.33        16.51        4701
103 15.89       15.47       15.47        5.39        16.92        5071
104 15.85       15.53       15.82        5.50        17.16        4970
    tourist_nights households_2021 rented_households_2021 dwellings_2022
1        NA         90671           13534                 156185
2    860775         90671           13534                 156185
3    928528         90671           13534                 156185
4    985240         90671           13534                 156185
5        NA        149713           27256                 202322
6   1058649        149713           27256                 202322
7   1119300        149713           27256                 202322
8   1167899        149713           27256                 202322
9        NA        153389           34832                 200498
10   584132        153389           34832                 200498
11   651823        153389           34832                 200498
12   674977        153389           34832                 200498
13       NA        681349          186037                 842440
14  7470106        681349          186037                 842440
15  8898492        681349          186037                 842440
16  9514850        681349          186037                 842440
17       NA         35735            3427                  73457
18   293084         35735            3427                  73457
19   318180         35735            3427                  73457
20   338972         35735            3427                  73457
21       NA        148102           25918                 205637
22   443278        148102           25918                 205637
23   446775        148102           25918                 205637
24   487280        148102           25918                 205637
25       NA         75043            9621                 140855
26   589456         75043            9621                 140855
27   620384         75043            9621                 140855
28   649721         75043            9621                 140855
29       NA         45428            5627                  87506
30   257165         45428            5627                  87506
⋮   ⋮              ⋮               ⋮                      ⋮
75   436020         47386           5464                   85508
76   472961         47386           5464                   85508
77       NA         43925           8448                   81295
78   450121         43925           8448                   81295
79   457538         43925           8448                   81295
80   478683         43925           8448                   81295
81       NA         63726          13350                   99103
82   918909         63726          13350                   99103
83  1016851         63726          13350                   99103
84  1064856         63726          13350                   99103
85       NA        146273          25961                  229656
86  1414061        146273          25961                  229656
87  1606783        146273          25961                  229656
88  1593554        146273          25961                  229656
89       NA         87423          12803                  144739
90  1127158         87423          12803                  144739
91  1448542         87423          12803                  144739
92  1606495         87423          12803                  144739
93       NA         95989          15843                  137296
94   229741         95989          15843                  137296
95   264230         95989          15843                  137296
96   282129         95989          15843                  137296
97       NA         85074          14653                  113945
98  2458031         85074          14653                  113945
99  2742352         85074          14653                  113945
100 3027576         85074          14653                  113945
101      NA         94792          16723                  132097
102 8380533         94792          16723                  132097
103 9243970         94792          16723                  132097
104 9552517         94792          16723                  132097

## 9. Quick checks

How many rows do we have, and how many missing values per column? We expect 104 rows (26 regions x 4 years) and missing values only in `tourist_nights` (2021) and `foreign_residents` (2024): 26 each. Every other column, including the new ones, should be complete.

In [19]:
nrow(merged)
n_distinct(merged$nuts_code)

# There must be exactly one row per region and year (this should print 0).
merged |> count(nuts_code, year) |> filter(n > 1) |> nrow()

merged |>
  summarise(across(everything(), ~ sum(is.na(.x)))) |>
  pivot_longer(everything(), names_to = "column", values_to = "missing")

[1] 104

[1] 26

[1] 0

   column                 missing
1  nuts_code               0
2  region                  0
3  year                    0
4  wage_monthly            0
5  income_median           0
6  rent_m2                 0
7  sale_price_m2           0
8  homes_completed         0
9  homes_licensed          0
10 foreign_residents      26
11 population              0
12 share_0_14              0
13 share_15_24             0
14 share_25_34             0
15 share_35_44             0
16 share_45_54             0
17 share_55_64             0
18 share_65_79             0
19 share_80plus            0
20 share_20_34             0
21 net_migration           0
22 tourist_nights         26
23 households_2021         0
24 rented_households_2021  0
25 dwellings_2022          0

Do all the regions of each table exist in our region list? Each of these should show zero rows (otherwise a code did not match).

In [20]:
wage          |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
income        |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
rent          |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
sales         |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
permits       |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
foreign       |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
population    |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
net_migration |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
tenure        |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
stock         |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)
stays         |> anti_join(regions, by = "nuts_code") |> distinct(nuts_code)

# Every region should have 4 years of tourism data (2022-2025), Lisbon (1A0, 1B0) included.
stays |> count(nuts_code) |> filter(n != 4)

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

   nuts_code
1  PT
2  1
3  11
4  19
5  1D
6  1A
7  1B
8  1C
9  15
10 2
11 3

     nuts_code

     nuts_code n

Spot checks against the original files:

- Porto Metropolitan Area (`11A`) in 2024: monthly wage 1620.1, rent 9.14, sale price 1986 and 5804 new homes.
- Grande Lisboa (`1A0`) in 2024: population 2,419,228, net migration 56,494, 1,072,111 dwellings in 2022 and 31.4% of households renting.
- Algarve (`150`) in 2024: population 577,095.

In [21]:
merged |>
  filter(nuts_code == "11A", year == 2024) |>
  select(nuts_code, year, wage_monthly, rent_m2, sale_price_m2, homes_completed)

merged |>
  filter(nuts_code %in% c("1A0", "150"), year == 2024) |>
  transmute(nuts_code, population, net_migration, dwellings_2022,
            rented_share = round(rented_households_2021 / households_2021 * 100, 1))

  nuts_code year wage_monthly rent_m2 sale_price_m2 homes_completed
1 11A       2024 1620.1       9.14    1986          5804

  nuts_code population net_migration dwellings_2022 rented_share
1 150        577095    14459          393387        23.0
2 1A0       2419228    56494         1072111        31.4

### Check: does the ranking change with the median income instead of the average wage?

The rent effort in the figure is the monthly rent of an 80 m² home divided by the average monthly wage. As a check we repeat it with the median declared income (annual, per taxpayer, from tax returns): rent x 12 / income. Its levels are higher, because the median is lower than the average and it includes pensioners, so we only compare the **ranking** of the regions with a Spearman correlation. A value close to 1 means the same regions come out on top either way.

In [22]:
effort_check <- merged |>
  filter(year %in% c(2021, 2024)) |>
  transmute(
    nuts_code, year,
    effort_wage   = rent_m2 * 80 / wage_monthly * 100,
    effort_income = rent_m2 * 80 * 12 / income_median * 100
  ) |>
  pivot_wider(names_from = year, values_from = c(effort_wage, effort_income))

# Same order of regions in 2024?
cor(effort_check$effort_wage_2024, effort_check$effort_income_2024, method = "spearman")

# Same regions getting worse between 2021 and 2024?
cor(effort_check$effort_wage_2024 - effort_check$effort_wage_2021,
    effort_check$effort_income_2024 - effort_check$effort_income_2021, method = "spearman")

[1] 0.9835897

[1] 0.9760684

## 10. Save the result

In [23]:
write_csv(merged, "data/datos_unidos.csv")