# Juntar as tabelas do INE

Junta os CSV do INE (e o da AIMA) num só ficheiro: `data/T06_merged_data.csv`.

## 1. Bibliotecas

In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## 2. Funções para ler os ficheiros do INE

In [2]:
ler_linhas_ine <- function(ficheiro) {
  todas_linhas <- read_lines(ficheiro, locale = locale(encoding = "latin1"))

  # só as linhas que começam com um código de região ("PT: ", "11A: ", ...)
  e_dados <- str_detect(todas_linhas, "^(\\d{4})?;?[0-9A-Z]{1,4}: ")

  read_delim(
    I(todas_linhas[e_dados]),
    delim = ";",
    col_names = FALSE,
    col_types = cols(.default = col_character()),
    show_col_types = FALSE
  )
}

# vírgula decimal -> número
para_numero <- function(x) round(parse_number(x, locale = locale(decimal_mark = ",")), 2)

## 3. Regiões (NUTS III e ilhas)

In [3]:
regioes <- ler_linhas_ine("data/T06_homes_completed.csv") |>
  select(X1) |>
  separate(X1, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  filter(nchar(nuts_code) == 3 | nuts_code %in% c("20", "30"))

regioes

   nuts_code region
1  111       Alto Minho
2  112       Cávado
3  119       Ave
4  11A       Área Metropolitana do Porto
5  11B       Alto Tâmega e Barroso
6  11C       Tâmega e Sousa
7  11D       Douro
8  11E       Terras de Trás-os-Montes
9  191       Região de Aveiro
10 192       Região de Coimbra
11 193       Região de Leiria
12 194       Viseu Dão Lafões
13 195       Beira Baixa
14 196       Beiras e Serra da Estrela
15 1D1       Oeste
16 1D2       Médio Tejo
17 1D3       Lezíria do Tejo
18 1A0       Grande Lisboa
19 1B0       Península de Setúbal
20 1C1       Alentejo Litoral
21 1C2       Baixo Alentejo
22 1C3       Alto Alentejo
23 1C4       Alentejo Central
24 150       Algarve
25 20        Região Autónoma dos Açores
26 30        Região Autónoma da Madeira

## 4. Tabelas com um valor por ano

O `passo` é 5 nas licenças e nos preços de venda (cada ano tem 5 colunas e ficamos com a primeira, o total).

In [4]:
ler_tabela_anual <- function(ficheiro, anos, nome_coluna, passo = 1) {
  colunas_dos_anos <- 2 + (seq_along(anos) - 1) * passo

  ler_linhas_ine(ficheiro) |>
    select(all_of(c(1, colunas_dos_anos))) |>
    set_names(c("region_raw", anos)) |>
    separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
    pivot_longer(-c(nuts_code, region), names_to = "year", values_to = "valor") |>
    mutate(year = as.integer(year), valor = para_numero(valor)) |>
    select(nuts_code, year, valor) |>
    set_names(c("nuts_code", "year", nome_coluna))
}

salario      <- ler_tabela_anual("data/T06_average_wage.csv",      2024:2021, "wage_monthly")
rendimento   <- ler_tabela_anual("data/T06_median_income.csv",     2024:2018, "income_median")
renda        <- ler_tabela_anual("data/T06_median_rent_m2.csv",    2025:2020, "rent_m2")
casas        <- ler_tabela_anual("data/T06_homes_completed.csv",   2025:2011, "homes_completed")
estrangeiros <- ler_tabela_anual("data/T06_foreign_residents.csv", 2023:2021, "foreign_residents")
migracao     <- ler_tabela_anual("data/T06_net_migration.csv",     2025:2021, "net_migration")

licencas <- ler_tabela_anual("data/T06_homes_licensed.csv", 2025:2002, "homes_licensed", passo = 5)
vendas   <- ler_tabela_anual("data/T06_sale_price_m2.csv",  2025:2019, "sale_price_m2",   passo = 5)

# os Açores aparecem duas vezes na renda (20 e 200)
renda <- renda |> filter(nuts_code != "200")

salario
renda

    nuts_code year wage_monthly
1   PT        2024 1576.0
2   PT        2023 1460.8
3   PT        2022 1362.4
4   PT        2021 1289.5
5   1         2024 1582.7
6   1         2023 1466.7
7   1         2022 1368.0
8   1         2021 1294.1
9   11        2024 1474.7
10  11        2023 1348.7
11  11        2022 1253.5
12  11        2021 1187.2
13  111       2024 1340.1
14  111       2023 1237.7
15  111       2022 1154.3
16  111       2021 1095.0
17  112       2024 1403.3
18  112       2023 1276.5
19  112       2022 1183.1
20  112       2021 1134.3
21  119       2024 1321.7
22  119       2023 1215.1
23  119       2022 1132.3
24  119       2021 1080.8
25  11A       2024 1620.1
26  11A       2023 1480.1
27  11A       2022 1378.6
28  11A       2021 1301.1
29  11B       2024 1207.1
30  11B       2023 1128.2
⋮   ⋮         ⋮    ⋮
119 1C3       2022 1126.6
120 1C3       2021 1078.9
121 1C4       2024 1372.0
122 1C4       2023 1271.7
123 1C4       2022 1190.6
124 1C4       2021 1127.3
125 15        2024 1320.2
126 15        2023 1238.7
127 15        2022 1150.8
128 15        2021 1106.3
129 150       2024 1320.2
130 150       2023 1238.7
131 150       2022 1150.8
132 150       2021 1106.3
133 2         2024 1431.9
134 2         2023 1315.1
135 2         2022 1191.1
136 2         2021 1126.1
137 20        2024 1431.9
138 20        2023 1315.1
139 20        2022 1191.1
140 20        2021 1126.1
141 3         2024 1406.8
142 3         2023 1324.0
143 3         2022 1244.1
144 3         2021 1212.4
145 30        2024 1406.8
146 30        2023 1324.0
147 30        2022 1244.1
148 30        2021 1212.4

    nuts_code year rent_m2
1   PT        2025 9.29
2   PT        2024 8.47
3   PT        2023 7.62
4   PT        2022 6.88
5   PT        2021 6.31
6   PT        2020 5.79
7   1         2025 9.32
8   1         2024 8.50
9   1         2023 7.64
10  1         2022 6.90
11  1         2021 6.34
12  1         2020 5.81
13  11        2025 8.00
14  11        2024 7.22
15  11        2023 6.48
16  11        2022 5.77
17  11        2021 5.29
18  11        2020 4.88
19  111       2025 6.51
20  111       2024 6.00
21  111       2023 5.35
22  111       2022 4.69
23  111       2021 4.29
24  111       2020 4.00
25  112       2025 7.83
26  112       2024 7.38
27  112       2023 6.59
28  112       2022 5.77
29  112       2021 5.14
30  112       2020 4.93
⋮   ⋮         ⋮    ⋮
193 150       2025 10.53
194 150       2024  9.74
195 150       2023  8.61
196 150       2022  7.70
197 150       2021  6.94
198 150       2020  6.73
199 2         2025  5.94
200 2         2024  5.46
201 2         2023  5.15
202 2         2022  4.90
203 2         2021  4.54
204 2         2020  4.47
205 20        2025  5.94
206 20        2024  5.46
207 20        2023  5.15
208 20        2022  4.90
209 20        2021  4.54
210 20        2020  4.47
211 3         2025 11.32
212 3         2024 10.61
213 3         2023  9.16
214 3         2022  7.86
215 3         2021  6.64
216 3         2020  6.32
217 30        2025 11.32
218 30        2024 10.61
219 30        2023  9.16
220 30        2022  7.86
221 30        2021  6.64
222 30        2020  6.32

## 5. População por idade

In [5]:
nomes_idades <- c("total", "a0_4", "a5_9", "a10_14", "a15_19", "a20_24", "a25_29", "a30_34",
                  "a35_39", "a40_44", "a45_49", "a50_54", "a55_59", "a60_64", "a65_69",
                  "a70_74", "a75_79", "a80_84", "a85_mais")

populacao_idades <- ler_linhas_ine("data/T06_population_by_age.csv") |>
  mutate(year = as.integer(X1)) |>
  fill(year) |>   # o ano só vem na primeira linha de cada bloco
  select(year, region_raw = X2, X3:X21) |>
  set_names(c("year", "region_raw", nomes_idades)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  mutate(across(total:a85_mais, para_numero))

populacao <- populacao_idades |>
  transmute(
    nuts_code, year,
    population   = total,
    share_0_14   = (a0_4 + a5_9 + a10_14) / total * 100,
    share_15_24  = (a15_19 + a20_24) / total * 100,
    share_25_34  = (a25_29 + a30_34) / total * 100,
    share_35_44  = (a35_39 + a40_44) / total * 100,
    share_45_54  = (a45_49 + a50_54) / total * 100,
    share_55_64  = (a55_59 + a60_64) / total * 100,
    share_65_79  = (a65_69 + a70_74 + a75_79) / total * 100,
    share_80plus = (a80_84 + a85_mais) / total * 100,
    share_20_34  = (a20_24 + a25_29 + a30_34) / total * 100
  ) |>
  mutate(across(starts_with("share_"), ~ round(.x, 2)))

populacao

    nuts_code year population share_0_14 share_15_24 share_25_34 share_35_44
1   PT        2025 11424031   12.36      10.30       12.80       13.33
2   1         2025 10912573   12.34      10.27       12.84       13.32
3   11        2025  3790554   11.79      10.16       12.19       12.83
4   111       2025   244343   11.41       9.57       10.90       12.25
5   112       2025   449945   12.81      10.92       12.65       13.64
6   119       2025   441329   12.18      10.06       12.15       13.00
7   11A       2025  1861727   11.79      10.11       12.72       13.19
8   11B       2025    83364    9.71       8.14        8.35       10.11
9   11C       2025   416728   12.11      10.91       12.28       12.62
10  11D       2025   184167   10.31       9.37        9.90       10.76
11  11E       2025   108951    9.63       9.51       10.57       10.19
12  19        2025  1771259   11.69       9.75       11.13       12.23
13  191       2025   400219   12.52      10.10       12.13       13.14
14  192       2025   467375   11.23       9.63       10.95       11.97
15  193       2025   319032   12.45      10.19       11.97       12.84
16  194       2025   267430   11.86       9.83       10.54       12.03
17  195       2025   104118   10.89       9.12       10.04       11.20
18  196       2025   213085   10.17       8.88        9.69       10.94
19  1D        2025   905403   12.59      10.30       11.81       12.71
20  1D1       2025   413287   12.74      10.31       12.31       13.18
21  1D2       2025   227067   12.06      10.00       10.65       11.80
22  1D3       2025   265049   12.80      10.54       12.03       12.74
23  1A        2025  2415261   13.16      10.74       15.31       14.69
24  1A0       2025  2415261   13.16      10.74       15.31       14.69
25  1B        2025   937678   13.64      11.11       13.49       14.06
26  1B0       2025   937678   13.64      11.11       13.49       14.06
27  1C        2025   514386   11.76       9.59       12.15       13.03
28  1C1       2025   118492   10.77       9.15       16.13       16.39
29  1C2       2025   125767   12.27       9.96       12.16       12.70
30  1C3       2025   108485   11.76       9.50        9.81       11.05
⋮   ⋮         ⋮    ⋮          ⋮          ⋮           ⋮           ⋮
156 11B       2021   81869     9.67       8.52        7.90       10.38
157 11C       2021  404148    12.94      12.05       11.63       13.09
158 11D       2021  180409    10.75       9.71        8.87       11.50
159 11E       2021  106574     9.72       9.81        9.06       10.82
160 19        2021 1667125    11.83       9.95        9.91       12.65
161 191       2021  372746    12.93      10.32       10.89       13.53
162 192       2021  442547    11.46       9.76        9.64       12.62
163 193       2021  293854    12.61      10.49       10.62       13.08
164 194       2021  251826    11.92      10.15        9.50       12.60
165 195       2021   98387    10.60       9.00        8.78       11.28
166 196       2021  207765    10.03       9.14        8.72       11.25
167 1D        2021  825229    12.84      10.40        9.91       12.94
168 1D1       2021  372933    13.31      10.55       10.36       13.52
169 1D2       2021  211231    11.72      10.04        9.22       11.84
170 1D3       2021  241065    13.10      10.50        9.84       12.99
171 1A        2021 2184555    14.30      10.67       13.04       14.39
172 1A0       2021 2184555    14.30      10.67       13.04       14.39
173 1B        2021  831113    14.61      10.78       11.16       14.13
174 1B0       2021  831113    14.61      10.78       11.16       14.13
175 1C        2021  485647    12.15       9.67       10.51       12.93
176 1C1       2021  104910    11.41       9.32       13.87       15.10
177 1C2       2021  118514    12.84       9.87       10.35       12.49
178 1C3       2021  106510    11.95       9.56        8.83       11.63
179 1C4       2021  155713    12.26       9.82        9.51       12.70
180 15        2021  507930    13.62       9.77       11.53       14.08
181 150       2021  507930    13.62       9.77       11.53       14.08
182 2         2021  241026    14.77      11.74       12.69       15.33
183 20        2021  241026    14.77      11.74       12.69       15.33
184 3         2021  253129    12.93      11.40       10.47       13.71
185 30        2021  253129    12.93      11.40       10.47       13.71
    share_45_54 share_55_64 share_65_79 share_80plus share_20_34
1   14.75       13.13       16.30        7.04        18.24
2   14.70       13.06       16.34        7.13        18.27
3   14.86       14.16       17.21        6.81        17.56
4   14.35       13.53       18.83        9.16        15.90
5   15.47       13.66       15.18        5.68        18.37
6   15.19       14.64       16.88        5.89        17.46
7   14.98       13.93       16.86        6.41        18.08
8   12.89       14.54       23.87       12.40        12.56
9   15.12       15.20       16.12        5.64        17.99
10  13.77       15.15       20.99        9.76        14.83
11  12.65       13.62       21.85       11.99        16.15
12  14.33       13.65       18.38        8.84        16.28
13  14.80       13.52       16.72        7.07        17.40
14  14.56       13.96       18.68        9.02        16.10
15  14.62       13.29       16.80        7.84        17.33
16  14.22       13.19       18.96        9.36        15.64
17  13.14       13.82       20.34       11.45        14.84
18  13.20       14.29       21.48       11.36        14.47
19  14.64       13.31       16.85        7.79        17.16
20  15.04       13.15       16.33        6.94        17.68
21  13.69       14.04       18.36        9.40        15.79
22  14.83       12.93       16.38        7.73        17.51
23  14.64       11.40       13.66        6.40        21.11
24  14.64       11.40       13.66        6.40        21.11
25  15.22       11.51       14.78        6.19        19.24
26  15.22       11.51       14.78        6.19        19.24
27  14.13       13.23       17.49        8.62        17.27
28  13.98       10.86       15.50        7.21        21.26
29  13.63       13.51       17.61        8.17        17.47
30  14.09       14.37       19.27       10.15        14.71
⋮   ⋮           ⋮           ⋮           ⋮            ⋮
156 12.70       15.73       23.24       11.86        12.19
157 15.82       14.90       14.24        5.33        18.02
158 14.05       15.88       19.81        9.42        13.91
159 12.70       14.59       21.78       11.53        14.75
160 14.38       14.22       18.28        8.78        15.14
161 15.07       13.92       16.44        6.89        16.32
162 14.60       14.43       18.59        8.89        14.81
163 14.73       13.86       16.87        7.74        16.09
164 13.92       13.72       19.08        9.11        14.72
165 13.25       14.61       20.24       12.24        13.62
166 13.24       15.24       21.01       11.37        13.58
167 14.79       13.80       17.32        7.99        15.21
168 15.13       13.43       16.80        6.90        15.70
169 14.12       14.82       18.35        9.90        14.40
170 14.87       13.48       17.23        7.99        15.16
171 14.61       11.81       14.84        6.34        18.64
172 14.61       11.81       14.84        6.34        18.64
173 14.97       12.28       16.08        5.98        16.57
174 14.97       12.28       16.08        5.98        16.57
175 13.91       14.09       17.39        9.35        15.58
176 13.05       13.01       16.24        8.00        19.08
177 13.74       14.26       17.52        8.94        15.48
178 13.98       14.78       18.49       10.79        13.68
179 14.59       14.22       17.33        9.57        14.59
180 14.80       13.39       16.53        6.27        16.49
181 14.80       13.39       16.53        6.27        16.49
182 15.05       13.55       12.67        4.20        18.75
183 15.05       13.55       12.67        4.20        18.75
184 16.09       15.20       14.87        5.33        16.19
185 16.09       15.20       14.87        5.33        16.19

## 6. Censos 2021 e parque habitacional 2022

In [6]:
# colunas: total, propriedade, arrendamento, outra situação
regime <- ler_linhas_ine("data/T06_households_tenure_2021.csv") |>
  select(region_raw = X1, households_2021 = X2, rented_households_2021 = X4) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  mutate(across(c(households_2021, rented_households_2021), para_numero)) |>
  select(nuts_code, households_2021, rented_households_2021)

parque <- ler_linhas_ine("data/T06_dwelling_stock_2022.csv") |>
  select(region_raw = X1, dwellings_2022 = X2) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  mutate(dwellings_2022 = para_numero(dwellings_2022)) |>
  select(nuts_code, dwellings_2022)

regime
parque

   nuts_code households_2021 rented_households_2021
1  PT        4142581         922810
2  1         3962715         891434
3  11        1379430         306252
4  111         90671          13534
5  112        149713          27256
6  119        153389          34832
7  11A        681349         186037
8  11B         35735           3427
9  11C        148102          25918
10 11D         75043           9621
11 11E         45428           5627
12 19         674187         104470
13 191        143268          25323
14 192        180264          29221
15 193        116340          17275
16 194        100823          13376
17 195         43234           5539
18 196         90258          13736
19 1D         329685          54607
20 1D1        146273          25961
21 1D2         87423          12803
22 1D3         95989          15843
23 1A         858646         269489
24 1A0        858646         269489
25 1B         332717          78505
26 1B0        332717          78505
27 1C         194655          33566
28 1C1         39618           6304
29 1C2         47386           5464
30 1C3         43925           8448
31 1C4         63726          13350
32 15         193395          44545
33 150        193395          44545
34 2           85074          14653
35 20          85074          14653
36 3           94792          16723
37 30          94792          16723

   nuts_code dwellings_2022
1  PT        6003809
2  1         5757767
3  11        1908900
4  111        156185
5  112        202322
6  119        200498
7  11A        842440
8  11B         73457
9  11C        205637
10 11D        140855
11 11E         87506
12 19        1102912
13 191        197876
14 192        285411
15 193        174368
16 194        172651
17 195         89254
18 196        183352
19 1D         511691
20 1D1        229656
21 1D2        144739
22 1D3        137296
23 1A        1072111
24 1A0       1072111
25 1B         431921
26 1B0        431921
27 1C         336845
28 1C1         70939
29 1C2         85508
30 1C3         81295
31 1C4         99103
32 15         393387
33 150        393387
34 2          113945
35 20         113945
36 3          132097
37 30         132097

## 7. Dormidas (de mensal para anual)

Somamos os meses de cada ano e ficamos com 2022 a 2025.

In [7]:
# linha dos meses: ";Agosto de 2026;Julho de 2026;..."
linhas_turismo <- read_lines("data/T06_tourist_nights.csv", locale = locale(encoding = "latin1"))
linha_meses    <- linhas_turismo[str_detect(linhas_turismo, "^;[^;]+ de \\d{4};")][1]

nomes_meses <- str_split(linha_meses, ";")[[1]]
nomes_meses <- nomes_meses[nomes_meses != ""]

dormidas_mensais <- ler_linhas_ine("data/T06_tourist_nights.csv") |>
  select(1:(length(nomes_meses) + 1)) |>
  set_names(c("region_raw", nomes_meses)) |>
  separate(region_raw, into = c("nuts_code", "region"), sep = ": ", extra = "merge") |>
  pivot_longer(-c(nuts_code, region), names_to = "month", values_to = "tourist_nights") |>
  mutate(
    year = as.integer(str_extract(month, "\\d{4}")),
    tourist_nights = para_numero(tourist_nights)
  )

dormidas <- dormidas_mensais |>
  inner_join(regioes |> select(nuts_code), by = "nuts_code") |>
  filter(year >= 2022, year <= 2025) |>
  group_by(nuts_code, year) |>
  summarise(tourist_nights = sum(tourist_nights), .groups = "drop")

dormidas

    nuts_code year tourist_nights
1   111       2022  860775
2   111       2023  928528
3   111       2024  985240
4   111       2025 1031079
5   112       2022 1058649
6   112       2023 1119300
7   112       2024 1167899
8   112       2025 1183221
9   119       2022  584132
10  119       2023  651823
11  119       2024  674977
12  119       2025  698406
13  11A       2022 7470106
14  11A       2023 8898492
15  11A       2024 9514850
16  11A       2025 9973516
17  11B       2022  293084
18  11B       2023  318180
19  11B       2024  338972
20  11B       2025  363638
21  11C       2022  443278
22  11C       2023  446775
23  11C       2024  487280
24  11C       2025  517475
25  11D       2022  589456
26  11D       2023  620384
27  11D       2024  649721
28  11D       2025  668247
29  11E       2022  257165
30  11E       2023  279134
⋮   ⋮         ⋮    ⋮
75  1C2       2024  472961
76  1C2       2025  510875
77  1C3       2022  450121
78  1C3       2023  457538
79  1C3       2024  478683
80  1C3       2025  480475
81  1C4       2022  918909
82  1C4       2023 1016851
83  1C4       2024 1064856
84  1C4       2025 1114694
85  1D1       2022 1414061
86  1D1       2023 1606783
87  1D1       2024 1593554
88  1D1       2025 1596723
89  1D2       2022 1127158
90  1D2       2023 1448542
91  1D2       2024 1606495
92  1D2       2025 1631345
93  1D3       2022  229741
94  1D3       2023  264230
95  1D3       2024  282129
96  1D3       2025  277164
97  20        2022 2458031
98  20        2023 2742352
99  20        2024 3027576
100 20        2025 3109259
101 30        2022 8380533
102 30        2023 9243970
103 30        2024 9552517
104 30        2025 9926753

## 8. Estrangeiros residentes em 2024 (AIMA)

Este ficheiro só tem 2024 e está em UTF-8, por isso lemos com `read_csv`.

In [8]:
estrangeiros_aima <- read_csv(
  "data/T06_foreign_residents_aima_2024.csv",
  col_types = cols(nuts_code = col_character()),
  show_col_types = FALSE
) |>
  select(nuts_code, year, foreign_residents_aima_2024)

# 26 regiões, sem repetidas e iguais às da nossa lista
stopifnot(
  nrow(estrangeiros_aima) == 26,
  !anyDuplicated(estrangeiros_aima$nuts_code),
  all(estrangeiros_aima$year == 2024),
  setequal(estrangeiros_aima$nuts_code, regioes$nuts_code)
)

estrangeiros_aima

   nuts_code year foreign_residents_aima_2024
1  111       2024  20190
2  112       2024  41510
3  119       2024  21535
4  11A       2024 160957
5  11B       2024   3006
6  11C       2024  12999
7  11D       2024   7765
8  11E       2024   8674
9  150       2024 167321
10 191       2024  38270
11 192       2024  44068
12 193       2024  38375
13 194       2024  18085
14 195       2024  10043
15 196       2024  14430
16 1A0       2024 574895
17 1B0       2024 159239
18 1C1       2024  32971
19 1C2       2024  14609
20 1C3       2024   6170
21 1C4       2024  11754
22 1D1       2024  56632
23 1D2       2024  21166
24 1D3       2024  31892
25 20        2024   8197
26 30        2024  18944

## 9. Juntar tudo

Onde não há dados fica `NA`.

In [9]:
esqueleto <- expand_grid(regioes, year = 2021:2024)

unido <- esqueleto |>
  left_join(salario,       by = c("nuts_code", "year")) |>
  left_join(rendimento,    by = c("nuts_code", "year")) |>
  left_join(renda,         by = c("nuts_code", "year")) |>
  left_join(vendas,        by = c("nuts_code", "year")) |>
  left_join(casas,         by = c("nuts_code", "year")) |>
  left_join(licencas,      by = c("nuts_code", "year")) |>
  left_join(estrangeiros,  by = c("nuts_code", "year")) |>
  left_join(populacao,     by = c("nuts_code", "year")) |>
  left_join(migracao,      by = c("nuts_code", "year")) |>
  left_join(dormidas,      by = c("nuts_code", "year")) |>
  left_join(regime,        by = "nuts_code") |>   # repetido em todos os anos
  left_join(parque,        by = "nuts_code") |>   # repetido em todos os anos
  left_join(estrangeiros_aima, by = c("nuts_code", "year")) |>
  arrange(nuts_code, year)

glimpse(unido)

Rows: 104
Columns: 26
$ nuts_code                   <chr> "111", "111", "111", "111", "112", "112", …
$ region                      <chr> "Alto Minho", "Alto Minho", "Alto Minho", …
$ year                        <dbl> 2021, 2022, 2023, 2024, 2021, 2022, 2023, …
$ wage_monthly                <dbl> 1095.0, 1154.3, 1237.7, 1340.1, 1134.3, 11…
$ income_median               <dbl> 9427, 9993, 10755, 11646, 9897, 10474, 112…
$ rent_m2                     <dbl> 4.29, 4.69, 5.35, 6.00, 5.14, 5.77, 6.59, …
$ sale_price_m2               <dbl> 945, 1064, 1108, 1248, 1091, 1230, 1385, 1…
$ homes_completed             <dbl> 588, 596, 581, 656, 1362, 1706, 1465, 1471…
$ homes_licensed              <dbl> 745, 888, 1108, 941, 1754, 2008, 2066, 214…
$ foreign_residents           <dbl> 7505, 9187, 13145, NA, 16781, 19947, 28650…
$ population                  <dbl> 230770, 236830, 241424, 243852, 417412, 43…
$ share_0_14                  <dbl> 11.57, 11.65, 11.58, 11.52, 13.54, 13.54, …
$ share_15_24                 <dbl> 9.77, 9.91, 9.87, 9.77, 11.45, 11.42, 11.3…
$ share_25_34                 <dbl> 9.96, 10.41, 10.77, 10.85, 11.82, 12.20, 1…
$ share_35_44                 <dbl> 12.59, 12.54, 12.46, 12.35, 14.22, 14.04, …
$ share_45_54                 <dbl> 14.34, 14.28, 14.28, 14.29, 15.62, 15.55, …
$ share_55_64                 <dbl> 14.05, 13.80, 13.61, 13.55, 13.66, 13.50, …
$ share_65_79                 <dbl> 18.75, 18.63, 18.65, 18.73, 14.31, 14.43, …
$ share_80plus                <dbl> 8.96, 8.78, 8.78, 8.93, 5.38, 5.32, 5.38, …
$ share_20_34                 <dbl> 15.03, 15.60, 16.00, 16.00, 17.78, 18.22, …
$ net_migration               <dbl> 124, 7788, 6096, 4102, -314, 13745, 10181,…
$ tourist_nights              <dbl> NA, 860775, 928528, 985240, NA, 1058649, 1…
$ households_2021             <dbl> 90671, 90671, 90671, 90671, 149713, 149713…
$ rented_households_2021      <dbl> 13534, 13534, 13534, 13534, 27256, 27256, …
$ dwellings_2022              <dbl> 156185, 156185, 156185, 156185, 202322, 20…
$ foreign_residents_aima_2024 <dbl> NA, NA, NA, 20190, NA, NA, NA, 41510, NA, …

## 10. Verificações

Devem ser 104 linhas, 26 regiões e 0 linhas repetidas.

In [10]:
nrow(unido)
n_distinct(unido$nuts_code)
unido |> count(nuts_code, year) |> filter(n > 1) |> nrow()

unido |>
  summarise(across(everything(), ~ sum(is.na(.x)))) |>
  pivot_longer(everything(), names_to = "column", values_to = "missing")

[1] 104

[1] 26

[1] 0

   column                      missing
1  nuts_code                    0
2  region                       0
3  year                         0
4  wage_monthly                 0
5  income_median                0
6  rent_m2                      0
7  sale_price_m2                0
8  homes_completed              0
9  homes_licensed               0
10 foreign_residents           26
11 population                   0
12 share_0_14                   0
13 share_15_24                  0
14 share_25_34                  0
15 share_35_44                  0
16 share_45_54                  0
17 share_55_64                  0
18 share_65_79                  0
19 share_80plus                 0
20 share_20_34                  0
21 net_migration                0
22 tourist_nights              26
23 households_2021              0
24 rented_households_2021       0
25 dwellings_2022               0
26 foreign_residents_aima_2024 78

Cada tabela tem as 26 regiões? Tem de dar 0 em todas.

In [11]:
tabelas <- list(
  salario = salario, rendimento = rendimento, renda = renda, vendas = vendas,
  licencas = licencas, estrangeiros = estrangeiros, populacao = populacao,
  migracao = migracao, regime = regime, parque = parque, dormidas = dormidas,
  estrangeiros_aima = estrangeiros_aima
)

for (nome in names(tabelas)) {
  regioes_em_falta <- setdiff(regioes$nuts_code, tabelas[[nome]]$nuts_code)
  cat(nome, ":", length(regioes_em_falta), "regiões em falta\n")
}

# 4 anos de turismo por região (2022-2025)
dormidas |> count(nuts_code) |> filter(n != 4)

salario : 0 regiões em falta
rendimento : 0 regiões em falta
renda : 0 regiões em falta
vendas : 0 regiões em falta
licencas : 0 regiões em falta
estrangeiros : 0 regiões em falta
populacao : 0 regiões em falta
migracao : 0 regiões em falta
regime : 0 regiões em falta
parque : 0 regiões em falta
dormidas : 0 regiões em falta
estrangeiros_aima : 0 regiões em falta

     nuts_code n

Comparação com os ficheiros originais, em 2024.

In [12]:
# 11A: salário 1620.1, renda 9.14, venda 1986, 5804 casas
unido |>
  filter(nuts_code == "11A", year == 2024) |>
  select(nuts_code, year, wage_monthly, rent_m2, sale_price_m2, homes_completed)

# 1A0: população 2419228, migração 56494, 1072111 alojamentos, 31.4% a arrendar, AIMA 574895
# 150: população 577095, AIMA 167321
unido |>
  filter(nuts_code %in% c("1A0", "150"), year == 2024) |>
  transmute(nuts_code, population, net_migration, dwellings_2022,
            rented_share = round(rented_households_2021 / households_2021 * 100, 1),
            foreign_residents_aima_2024)

  nuts_code year wage_monthly rent_m2 sale_price_m2 homes_completed
1 11A       2024 1620.1       9.14    1986          5804

  nuts_code population net_migration dwellings_2022 rented_share
1 150        577095    14459          393387        23.0
2 1A0       2419228    56494         1072111        31.4
  foreign_residents_aima_2024
1 167321
2 574895

### O ranking muda com o rendimento mediano?

Comparamos a ordem das regiões com a correlação de Spearman. Perto de 1 quer dizer que é a mesma.

In [13]:
esforco <- unido |>
  filter(year %in% c(2021, 2024)) |>
  transmute(
    nuts_code, year,
    esforco_salario    = rent_m2 * 80 / wage_monthly * 100,
    esforco_rendimento = rent_m2 * 80 * 12 / income_median * 100
  ) |>
  pivot_wider(names_from = year, values_from = c(esforco_salario, esforco_rendimento))

# ordem em 2024
cor(esforco$esforco_salario_2024, esforco$esforco_rendimento_2024, method = "spearman")

# regiões que pioraram entre 2021 e 2024
cor(esforco$esforco_salario_2024 - esforco$esforco_salario_2021,
    esforco$esforco_rendimento_2024 - esforco$esforco_rendimento_2021, method = "spearman")

[1] 0.9835897

[1] 0.9760684

## 11. Guardar

In [14]:
write_csv(unido, "data/T06_merged_data.csv")